type Post {
  _id: ID!
  title: String!
  content: String!
  author: User!
}

input PostInput {
  title: String!
  content: String!
  author: ID!
}

type Query {
  posts: [Post!]! # recebe um array de usuarios
  post(id: ID!): Post! # recebe um id e retorna um unico usuario
}

type Mutation {
  createPost(data: PostInput!): Post! # retorna os dados do usuario criado
  updatePost(id: ID, data: PostInput!): Post!
  deletePost(id: ID!): Boolean # retorna se deletou ou nao true|false
}
