type User {
  _id: ID!
  firstName: String!
  lastName: String!
  fullName: String!
  email: String
  active: Boolean!
}

input UserInput {
  firstName: String!
  lastName: String!
  email: String
  active: Boolean!
}

type Query {
  users: [User!]! # recebe um array de usuarios
  user(id: ID!): User! # recebe um id e retorna um unico usuario
}

type Mutation {
  createUser(data: UserInput!): User! # retorna os dados do usuario criado
  updateUser(id: ID, data: UserInput!): User!
  deleteUser(id: ID!): Boolean # retorna se deletou ou nao true|false
}
